server:
  port: 8083
  servlet:
    context-path: /mongodb
spring:
  application:
    name: mongodb-spring-boot-starter

  # mongodb
  data:
    mongodb:
      uri: mongodb+srv://luna:luna@cluster0.pas77.mongodb.net/luna?retryWrites=true&w=majority

#      username: luna
#      password: luna
#      host: 106.14.30.12
#      database: test

